[pytest]
testpaths = test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v -s --strict-markers

filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning

markers =
    smoke: 冒烟测试用例
    regress: 回归测试用例

alluredir = allure-results